# Built with Jekyll 3.6.0

# Setup
title:               "Poesía de Juana Borrero"
tagline:             (1877-1896) 
description:         Juana Borrero fue una pintora y poeta modernista cubana. Vivió poco más de 18 años y creó numerosos cuadros y poemas. Hoy perduran principalmente sus poemas y unos pocos cuadros y dibujos. Oriunda de Santo Suárez, La Habana (entonces colonia española), en 1895 Juana emigró a Cayo Hueso, Florida por los lazos que su padre Esteban Borrero mantenía con la causa independentista cubana. Se dice, aunque no está comprobado, que Juana y su padre viajaron a Nueva York en 1892, y que José Martí organizó una cena en su honor, donde Juana leyó el poema "Esperad" en frente de combatientes exiliados cubanos, quizás compuesto para la ocasión. En 1894, se publicó en La Habana el poemario _Rimas_, que Rubén Darío describió como "el libro raro de las poesías de Juana Borrero".
url:                 https://eluispr.github.io/juana/
baseurl:             '/juana'

# About/contact
author:              Juana Borrero
  name:              Luis Prieto 
  url:               
  email:             lpriet9@gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: /cyan

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
