# Site Metadata
title: "Poesía de Juana Borrero"
tagline: "(1877-1896)"
description: "Una colección de los poemas y obras de Juana Borrero, pintora y poeta modernista cubana."
baseurl: "/juana"

# Author Information
author:              
  name: "Luis Prieto"
  url: "https://eluispr.github.io/juana"
  email: "lpriet9@gmail.com"

# Color Scheme Options: red, orange, magenta, cyan, blue, brown
color-scheme: "blue"

# Permalinks
permalink: "/:title/"

# Site Encoding
encoding: "utf-8"

# Text Collections
collections:
  texts:
    output: true
    permalink: "/texts/:title/"

# Markdown Processor and Settings
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final build
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme Configurations
# Uncomment this if using the Ed theme locally or on a custom server
# theme: "ed."

# GitHub Deployments: Use this for deploying to GitHub Pages
remote_theme: "minicomp/ed"
