# Site Metadata
title:               "Poesía de Juana Borrero"
tagline:             "(1877-1896)"
description:         "Una colección de los poemas y obras de Juana Borrero, pintora y poeta modernista cubana."
baseurl:             "/juana"
url:                 "https://eluispr.github.io"

# Author Information
author:
  name:              "Luis Prieto"
  url:               "https://eluispr.github.io/juana"
  email:             "lpriet9@gmail.com"

# Theme Configuration
remote_theme: "minicomp/ed"

# Text Collections Configuration
collections:
  texts:
    output: true
    permalink: "/texts/:title/"

# Markdown Processor and Options
markdown: kramdown

kramdown:
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  footnote_backlink: "&#x21a9;&#xfe0e;"
  enable_coderay: false

# Permalinks Configuration
permalink: pretty
permalink: /:title/

# Color scheme for the theme: red, orange, magenta, cyan, blue, brown
color-scheme:

# Exclusions from the build
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json
